application: px2-malu-me
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /fetch\.py
  script: wsgi.app
  secure: optional

- url: /2
  script: comp.gae_application
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
